name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install  # Instala las dependencias de package.json

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy with Railway
        run: railway up --service hapless-dogs
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
